apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dhis2-core-helm.fullname" . }}
  labels:
    {{- include "dhis2-core-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dhis2-core-helm.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if eq .Values.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
    {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dhis2-core-helm.selectorLabels" . | nindent 8 }}
      {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dhis2-core-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: copy-ro-config
          image: busybox
          command: ['sh', '-c', 'cp -v /dhis-conf-ro/* /dhis-conf-rw/ && cp -v /dhis-google-auth-json-ro/* /dhis-conf-rw/ && cp -v /server-xml-ro/* /server-xml-rw/']
          volumeMounts:
            - name: dhis-conf-ro
              mountPath: /dhis-conf-ro
            - name: dhis-conf-rw
              mountPath: /dhis-conf-rw

            - name: dhis-google-auth-json-ro
              mountPath: /dhis-google-auth-json-ro

            - name: server-xml-rw
              mountPath: /server-xml-rw
            - name: server-xml-ro
              mountPath: /server-xml-ro
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CATALINA_OPTS
              value: {{ .Values.catalinaOpts }}
            - name: JAVA_OPTS
              value: {{ .Values.javaOpts }}
            - name: DHIS2_HOME
              value: {{ .Values.dhis2Home }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            httpGet:
              path: {{ .Values.startupProbe.path }}
              port: http
          livenessProbe:
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
          volumeMounts:
            - name: dhis-conf-rw
              mountPath: {{ .Values.dhis2Home }}
              readOnly: false
            - name: server-xml-rw
              mountPath: /usr/local/tomcat/conf/server.xml
              subPath: server.xml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:

        - name: dhis-conf-rw
          emptyDir: { }
        - name: dhis-conf-ro
          configMap:
            name: {{ include "dhis2-core-helm.fullname" . }}
            items:
              - key: dhis.conf
                path: dhis.conf

        - name: dhis-google-auth-json-ro
          configMap:
            name: {{ include "dhis2-core-helm.fullname" . }}
            items:
              - key: dhis-google-auth.json
                path: dhis-google-auth.json

        - name: server-xml-rw
          emptyDir: {}
        - name: server-xml-ro
          configMap:
            name: {{ include "dhis2-core-helm.fullname" . }}
            items:
              - key: server.xml
                path: server.xml

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
