apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dhis2-core-helm.fullname" . }}
  labels:
    {{- include "dhis2-core-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dhis2-core-helm.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if eq .Values.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
    {{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dhis2-core-helm.selectorLabels" . | nindent 8 }}
      {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dhis2-core-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if or (not (or (hasKey .Values "minIO") (hasKey .Values "S3"))) .Values.initContainers }}
      initContainers:
      {{- with .Values.initContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not (or (hasKey .Values "minIO") (hasKey .Values "S3")) }}
        - name: dhis2-home-permissions
          image: busybox
          command: [ 'sh', '-c', 'mkdir -p {{ .Values.dhis2Home }} && chown {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }} {{ .Values.dhis2Home }} && chmod u+rw,go-rwx {{ .Values.dhis2Home }} && mkdir -p {{ .Values.dhis2Home }}/files && chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }} {{ .Values.dhis2Home }}/files && chmod -R u+rw,go-rwx {{ .Values.dhis2Home }}/files' ]
          volumeMounts:
            - name: dhis-home
              mountPath: {{ .Values.dhis2Home }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CATALINA_OPTS
              value: {{ .Values.catalinaOpts }}
            - name: JAVA_OPTS
              value: "-Dlog4j2.configurationFile={{ .Values.dhis2Home }}/log4j2.xml {{ .Values.javaOpts }}"
            - name: DHIS2_HOME
              value: {{ .Values.dhis2Home }}
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: {{ .Values.contextPath }}
          envFrom:
            - secretRef:
                name: {{ include "dhis2-core-helm.fullname" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            httpGet:
              path: {{ .Values.startupProbe.path }}
              port: http
          livenessProbe:
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
          volumeMounts:
{{- if not (or (hasKey .Values "minIO") (hasKey .Values "S3")) }}
            - name: dhis-home
              mountPath: {{ .Values.dhis2Home }}
              readOnly: false
{{- end }}
            - name: dhis-conf
              mountPath: {{ .Values.dhis2Home }}/dhis.conf
              subPath: dhis.conf
            - name: google-auth-json
              mountPath: {{ .Values.dhis2Home }}/dhis-google-auth.json
              subPath: dhis-google-auth.json
            - name: log4j2-xml
              mountPath: {{ .Values.dhis2Home }}/log4j2.xml
              subPath: log4j2.xml
            - name: server-xml
              mountPath: /usr/local/tomcat/conf/server.xml
              subPath: server.xml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
{{- if not (or (hasKey .Values "minIO") (hasKey .Values "S3")) }}
        - name: dhis-home
          persistentVolumeClaim:
            claimName: {{ include "dhis2-core-helm.fullname" . }}
{{- end }}
        - name: dhis-conf
          configMap:
            name: {{ include "dhis2-core-helm.fullname" . }}
            items:
              - key: dhis.conf
                path: dhis.conf
        - name: google-auth-json
          configMap:
            name: {{ include "dhis2-core-helm.fullname" . }}
            items:
              - key: dhis-google-auth.json
                path: dhis-google-auth.json
        - name: server-xml
          configMap:
            name: {{ include "dhis2-core-helm.fullname" . }}
            items:
              - key: server.xml
                path: server.xml
        - name: log4j2-xml
          configMap:
            name: {{ include "dhis2-core-helm.fullname" . }}
            items:
              - key: log4j2.xml
                path: log4j2.xml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
