apiVersion: skaffold/v4beta6
kind: Config
deploy:
  statusCheckDeadlineSeconds: 420
  helm:
    releases:
      - name: dhis2-postgresql
        namespace: dhis2
        createNamespace: true
        remoteChart: postgresql
        repo: https://charts.bitnami.com/bitnami
        version: 11.9.8
        valuesFiles:
          - ./postgresql.yaml

      - name: minio
        namespace: dhis2
        createNamespace: true
        remoteChart: minio
        repo: https://charts.bitnami.com/bitnami
        version: 14.7.5
        useHelmSecrets: true
        valuesFiles:
          - ./minio.yaml

      - name: dhis2-core
        namespace: dhis2
        createNamespace: true
        chartPath: charts/core
        valuesFiles:
          - ./dhis2.yaml
