apiVersion: skaffold/v4beta6
kind: Config
deploy:
  statusCheckDeadlineSeconds: 420
  helm:
    releases:
      - name: dhis2-postgresql
        namespace: dhis2
        createNamespace: true
        remoteChart: postgresql
        repo: https://charts.bitnami.com/bitnami
        version: 11.9.8
        valuesFiles:
          - ./values/postgresql.yaml

#      - name: dhis2-minio
#        namespace: dhis2
#        createNamespace: true
#        remoteChart: minio
#        repo: https://charts.bitnami.com/bitnami
#        version: 14.7.5
#        useHelmSecrets: true
#        valuesFiles:
#          - ./values/minio.yaml

      - name: dhis2-core
        namespace: dhis2
        createNamespace: true
        chartPath: charts/core
        valuesFiles:
          - ./values/dhis2.yaml
        setValueTemplates:
          ingress:
            enabled: true
            hostname: dhis2.dev.im.dhis2.org
            path: /core
            certIssuer: cert-issuer-prod
          startupProbe:
            path: /core
          livenessProbe:
            path: /core
          readinessProbe:
            path: /core
          environment:
            SERVER_SERVLET_CONTEXT_PATH: /core
          storage:
            className: gp2
