name: Build Chart

on:
  push:
    branches:
      - master
      - feature/**
    tags:
      - v*.*.*

  pull_request:

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find version
        run: |
          # Strip git ref prefix from version
          STRIPPED_REF=${GITHUB_REF##refs/*/}

          # Strip "v" prefix from tag name
          VERSION=${STRIPPED_REF#v}

          # Export
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          echo "VERSION=$VERSION"

      - name: Setup yq
        run: |
          wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq
          chmod +x /usr/bin/yq
        env:
          VERSION: v4.2.0
          BINARY: yq_linux_amd64

      - name: Update chart version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TARGET=./Chart.yaml
          yq -i e ".version = \"${{ env.VERSION }}\"" $TARGET
          [ "$(git diff --exit-code $TARGET)" != "0" ]

      - name: Helm Lint
        run: helm lint .

      - name: Helm package
        run: helm package .

      - name: Configure Git
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup Chart Releaser
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          wget https://github.com/helm/chart-releaser/releases/download/v${VERSION}/chart-releaser_${VERSION}_linux_amd64.tar.gz -O ./cr.tar.gz
          tar -xvf ./cr.tar.gz cr
          chmod +x cr
        env:
          VERSION: 1.2.0

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: ./cr upload --git-repo dhis2-core-helm --owner dhis2-sre --package-path . --token $GH_TOKEN
        env:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"

      - name: Update Helm Repository
        if: startsWith(github.ref, 'refs/tags/v')
        run: ./cr index --git-repo dhis2-core-helm --owner dhis2-sre --package-path . --push --token $GH_TOKEN --charts-repo https://github.com/dhis2-sre/dhis2-core-helm
        env:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"

      - name: Git...
        run: |
          git checkout -b tmp v${{ env.VERSION }}

      - uses: EndBug/add-and-commit@v9
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          default_author: github_actions
          message: Update helm repository index
          add: ".cr-index/index.yaml --allow-empty"

#      - name: Run chart-releaser
#        if: startsWith(github.ref, 'refs/tags/v')
#        uses: helm/chart-releaser-action@v1.4.0
#        with:
#          charts_dir: .
#        env:
#          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
